export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS';

export const HOMEWORKT_GET_ALLCOURSE='HOMEWORKT_GET_ALLCOURSE';
export const HOMEWORK_GET_LIST='HOMEWORK_GET_LIST';
export const HOMEWORK_SET_PAGES='HOMEWORK_SET_PAGES';
export const HOMEWORK_SET_COURSEID='HOMEWORK_SET_COURSEID';
export const HOMEWORKT_GET_SUBJECTLIST='HOMEWORKT_GET_SUBJECTLIST';
export const HOMEWORK_SET_SUBJECTLISTPAGES='HOMEWORK_SET_SUBJECTLISTPAGES';
export const HOMEWORKT_SET_SUBJECTLISTCOURSEID='HOMEWORKT_SET_SUBJECTLISTCOURSEID';
export const HOMEWORKT_GET_STUDENTHOMEWORLLIST='HOMEWORKT_GET_STUDENTHOMEWORLLIST';
export const HOMEWORKT_SET_STUDENTLISTPAGE='HOMEWORKT_SET_STUDENTLISTPAGE';

export const GRADE_GET_ALLSCORE='GRADE_GET_ALLSCORE';
export const GREADE_GET_DETAILSCORE='GREADE_GET_DETAILSCORE';
export const GRADE_SET_PAGESCORE = 'GRADE_SET_PAGESCORE';
export const GREADE_SET_SEARCHTERM='GREADE_SET_SEARCHTERM';
export const GREADE_SET_DETAILPAGE='GREADE_SET_DETAILPAGE';

export const DATA_GET_TABLE='DATA_GET_TABLE';
export const DATA_GET_IMAGES='DATA_GET_IMAGES';
export const DATA_SET_SEARCHTERM='DATA_SET_SEARCHTERM';
export const DATA_SET_SEARCHPAGE='DATA_SET_SEARCHPAGE';
export const DATA_SET_SEARCHID='DATA_SET_SEARCHID';


export const CASE_GET_TABLE='CASE_GET_TABLE';
export const CASE_SET_SEARCHTERM='CASE_SET_SEARCHTERM';
export const CASE_SET_SEARCHPAGE='CASE_SET_SEARCHPAGE';
export const CASE_UPDATE='CASE_UPDATE';

export const CASETABLE_GET_TABLE='CASETABLE_GET_TABLE';
export const CASETABLE_SET_SEARCHTERM='CASETABLE_SET_SEARCHTERM';
export const CASETABLE_SET_SEARCHPAGE='CASETABLE_SET_SEARCHPAGE';
export const CASETABLE_SET_SEARCHID='CASETABLE_SET_SEARCHID';


export const TRACK_GET_TABLE='TRACK_GET_TABLE';
export const TRACK_SET_SEARCHTERM='TRACK_SET_SEARCHTERM';
export const TRACK_SET_SEARCHPAGE='TRACK_SET_SEARCHPAGE';
export const TRACK_UPDATE='TRACK_UPDATE';

export const TRACKRESULT_GET_TABLE= 'TRACKRESULT_GET_TABLE';
export const TRACKRESULT_SET_SEARCHTERM= 'TRACKRESULT_SET_SEARCHTERM';
export const TRACKRESULT_SET_SEARCHPAGE= 'TRACKRESULT_SET_SEARCHPAGE';
export const TRACKRESULT_SET_SEARCHID= 'TRACKRESULT_SET_SEARCHID';
export const TRACKRESULT_UPDATE='TRACKRESULT_UPDATE';
export const TRACKRESULT_GET_MAPDATA='TRACKRESULT_GET_MAPDATA';

export const CHART_GET_TABLE='CHART_GET_TABLE';
export const CHART_SET_SEARCHTERM='CHART_SET_SEARCHTERM';

export const SELFINFO_GET_INFOLIST='SELFINFO_GET_INFOLIST';
export const SELFINFO_UPDATE_INFOLIST='SELFINFO_UPDATE_INFOLIST';