export default {
	theme:'dark',
	mode:'inline',
	navItems:[
		{
			header:'作业管理',
			router:'/homework',
			icon:'edit',
		},
		{
			header:'成绩查询',
			router:'/grade',
			icon:'solution',
		},
		{
			header:'测试题库',
			router:'/questionbank',
			icon:'switcher',
		},
		{
			header:'课程资源',
			router:'/resource',
			icon:'global',
		},
		{
			header:'论坛交流',
			router:'/tribune',
			icon:'github',
		}
	],
	navItemsT:[
        {
            header:'作业管理',
            router:'/homeworkt',
            icon:'edit',
        },
        {
            header:'成绩查询',
            router:'/gradet',
            icon:'solution',
        },
        {
            header:'测试题库',
            router:'/questionbankt',
            icon:'switcher',
        },
        {
            header:'课程资源',
            router:'/resourcet',
            icon:'global',
        },
        {
            header:'论坛交流',
            router:'/tribunet',
            icon:'github',
        }
	]
}